name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Benchmark
      run: go test -bench=. ./...

    - name: Race detection
      run: go test -race ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Test with coverage
      run: |
        go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.tmp ./...
        # Remove duplicate entries and keep the one with the highest count
        awk '
        BEGIN { print "mode: atomic" }
        NR > 1 {
            key = $1 ":" $2
            if (key in max_count) {
                if ($3 > max_count[key]) {
                    max_count[key] = $3
                    lines[key] = $0
                }
            } else {
                max_count[key] = $3
                lines[key] = $0
            }
        }
        END {
            for (key in lines) {
                print lines[key]
            }
        }
        ' coverage.tmp > coverage.out
        rm coverage.tmp

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
